// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 活动类型表
/// </summary>
[Table("activity_type")]
[Index("TypeName", Name = "uk_activity_type_name", IsUnique = true)]
public partial class ActivityType
{
    /// <summary>
    /// 活动类型ID
    /// </summary>
    [Key]
    [Column("activity_type_id")]
    public int ActivityTypeId { get; set; }

    /// <summary>
    /// 类型名称
    /// </summary>
    [Required]
    [Column("type_name")]
    [StringLength(30)]
    public string TypeName { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<ActivityEntity> Activities { get; set; } = new List<ActivityEntity>();
}