// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 商品状态表
/// </summary>
[Table("commodity_status")]
[Index("StatusName", Name = "uk_commodity_status_name", IsUnique = true)]
public partial class CommodityStatus
{
    /// <summary>
    /// 商品状态ID
    /// </summary>
    [Key]
    [Column("commodity_status_id")]
    public int CommodityStatusId { get; set; }

    /// <summary>
    /// 状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(30)]
    public string StatusName { get; set; }

    // Note: Commodity does not have a CommodityStatus navigation property,
    // so the InverseProperty on a collection here would cause EF Core model error.
    // Navigation removed; access statuses via DbSet<CommodityStatus> directly.
}