// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 商品订单状态表
/// </summary>
[Table("commodity_order_status")]
[Index("StatusName", Name = "uk_commodity_status_name", IsUnique = true)]
public partial class CommodityOrderStatus
{
    /// <summary>
    /// 商品订单状态ID
    /// </summary>
    [Key]
    [Column("order_status_id")]
    public int OrderStatusId { get; set; }

    /// <summary>
    /// 状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(30)]
    public string StatusName { get; set; }

    [InverseProperty("OrderStatus")]
    public virtual ICollection<CommodityOrder> CommodityOrders { get; set; } = new List<CommodityOrder>();
}