// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 菜品图片表
/// </summary>
[Table("dish_image")]
[Index("DishId", "SortOrder", Name = "idx_dish_image_dish")]
public partial class DishImage
{
    /// <summary>
    /// 图片ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 菜品ID
    /// </summary>
    [Column("dish_id")]
    public int DishId { get; set; }

    /// <summary>
    /// 图片地址
    /// </summary>
    [Required]
    [Column("image_url")]
    [StringLength(500)]
    public string ImageUrl { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    [Column("sort_order")]
    public int SortOrder { get; set; }

    /// <summary>
    /// 素材类型: 0=轮播图 1=规格图
    /// </summary>
    [Column("material_type")]
    public int MaterialType { get; set; } = 1;
}