// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 菜品分类状态表
/// </summary>
[Table("dish_category_status")]
[Index("StatusName", Name = "uk_dish_category_status_name", IsUnique = true)]
public partial class DishCategoryStatus
{
    /// <summary>
    /// 菜品分类状态ID
    /// </summary>
    [Key]
    [Column("dish_category_status_id")]
    public int DishCategoryStatusId { get; set; }

    /// <summary>
    /// 状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(30)]
    public string StatusName { get; set; }

    [InverseProperty("DishCategoryStatus")]
    public virtual ICollection<DishCategory> DishCategories { get; set; } = new List<DishCategory>();
}