// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 活动订单表
/// </summary>
[Table("activity_orders")]
[Index("CreateTime", Name = "idx_activity_orders_create_time")]
[Index("OrderStatusId", Name = "idx_activity_orders_status_id")]
[Index("UserId", Name = "idx_activity_orders_user_id")]
[Index("OrderNo", Name = "uk_activity_orders_order_no", IsUnique = true)]
public partial class ActivityOrder
{
    /// <summary>
    /// 活动订单ID
    /// </summary>
    [Key]
    [Column("order_id")]
    public long OrderId { get; set; }

    /// <summary>
    /// 平台订单号
    /// </summary>
    [Required]
    [Column("order_no")]
    [StringLength(64)]
    public string OrderNo { get; set; }

    /// <summary>
    /// 微信支付订单号
    /// </summary>
    [Column("wx_pay_no")]
    [StringLength(500)]
    public string WxPayNo { get; set; }

    /// <summary>
    /// 订单总金额
    /// </summary>
    [Column("total_amount")]
    [Precision(10, 2)]
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// 订单总人数
    /// </summary>
    [Column("total_quantity")]
    public int TotalQuantity { get; set; }

    /// <summary>
    /// 订单状态ID
    /// </summary>
    [Column("order_status_id")]
    public int OrderStatusId { get; set; }

    /// <summary>
    /// 下单人ID
    /// </summary>
    [Column("user_id")]
    public int UserId { get; set; }

    /// <summary>
    /// 下单时间
    /// </summary>
    [Column("create_time", TypeName = "datetime")]
    public DateTime CreateTime { get; set; }

    [InverseProperty("ActivityOrder")]
    public virtual ICollection<ActivityOrderDetail> ActivityOrderDetails { get; set; } = new List<ActivityOrderDetail>();

    [ForeignKey("OrderStatusId")]
    [InverseProperty("ActivityOrders")]
    public virtual ActivityOrderStatus OrderStatus { get; set; }
}