// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 活动状态表
/// </summary>
[Table("activity_status")]
[Index("StatusName", Name = "uk_activity_status_name", IsUnique = true)]
public partial class ActivityStatus
{
    /// <summary>
    /// 活动状态ID
    /// </summary>
    [Key]
    [Column("activity_status_id")]
    public int ActivityStatusId { get; set; }

    /// <summary>
    /// 状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(30)]
    public string StatusName { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<ActivityEntity> Activities { get; set; } = new List<ActivityEntity>();
}