// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 活动素材表
/// </summary>
[Table("activity_material")]
[Index("ActivityId", "SortOrder", Name = "idx_activity_material_activity")]
public partial class ActivityMaterial
{
    /// <summary>
    /// 素材ID
    /// </summary>
    [Key]
    [Column("activity_material_id")]
    public long ActivityMaterialId { get; set; }

    /// <summary>
    /// 活动ID
    /// </summary>
    [Column("activity_id")]
    public long ActivityId { get; set; }

    /// <summary>
    /// 素材类型 0图 1详情图 2视频
    /// </summary>
    [Required]
    [Column("material_type")]
    [StringLength(20)]
    public string MaterialType { get; set; }

    /// <summary>
    /// 素材地址
    /// </summary>
    [Required]
    [Column("material_url")]
    [StringLength(500)]
    public string MaterialUrl { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    [Column("sort_order")]
    public int SortOrder { get; set; }

    [ForeignKey("ActivityId")]
    [InverseProperty("ActivityMaterials")]
    public virtual ActivityEntity Activity { get; set; } // 类型改为 ActivityEntity
}