// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 商品订单明细表
/// </summary>
[Table("commodity_order_detail")]
[Index("CommodityId", Name = "idx_commodity_order_detail_commodity_id")]
[Index("OrderId", Name = "idx_commodity_order_detail_order_id")]
[Index("StatusId", Name = "idx_commodity_order_detail_status_id")]
public partial class CommodityOrderDetail
{
    /// <summary>
    /// 商品订单明细ID
    /// </summary>
    [Key]
    [Column("commodity_order_details_id")]
    public long CommodityOrderDetailsId { get; set; }

    /// <summary>
    /// 订单ID
    /// </summary>
    [Column("order_id")]
    public long OrderId { get; set; }

    /// <summary>
    /// 商品ID
    /// </summary>
    [Column("commodity_id")]
    public int CommodityId { get; set; }

    /// <summary>
    /// 商品单价
    /// </summary>
    [Column("unit_price")]
    [Precision(10, 2)]
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// 订购数量
    /// </summary>
    [Column("quantity")]
    public int Quantity { get; set; }

    /// <summary>
    /// 小计金额
    /// </summary>
    [Column("subtotal_amount")]
    [Precision(10, 2)]
    public decimal SubtotalAmount { get; set; }

    /// <summary>
    /// 商品状态ID
    /// </summary>
    [Column("status_id")]
    public int? StatusId { get; set; }

    [ForeignKey("CommodityId")]
    [InverseProperty("CommodityOrderDetails")]
    public virtual Commodity Commodity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("CommodityOrderDetails")]
    public virtual CommodityOrder Order { get; set; }
}