// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 商品标签中转表
/// </summary>
[Table("commodity_tag_detail")]
[Index("TagId", Name = "idx_commodity_tag_tag_id")]
[Index("CommodityId", "TagId", Name = "uk_commodity_tag", IsUnique = true)]
public partial class CommodityTagDetail
{
    /// <summary>
    /// 商品标签关联ID
    /// </summary>
    [Key]
    [Column("commodity_tag_relation_id")]
    public int CommodityTagRelationId { get; set; }

    /// <summary>
    /// 商品ID
    /// </summary>
    [Column("commodity_id")]
    public int CommodityId { get; set; }

    /// <summary>
    /// 标签ID
    /// </summary>
    [Column("tag_id")]
    public int TagId { get; set; }

    [ForeignKey("CommodityId")]
    [InverseProperty("CommodityTagDetails")]
    public virtual Commodity Commodity { get; set; }
}