// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 商品分类状态表
/// </summary>
[Table("commodity_category_status")]
[Index("StatusName", Name = "uk_category_status_name", IsUnique = true)]
public partial class CommodityCategoryStatus
{
    /// <summary>
    /// 分类状态ID
    /// </summary>
    [Key]
    [Column("category_status_id")]
    public int CategoryStatusId { get; set; }

    /// <summary>
    /// 状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(30)]
    public string StatusName { get; set; }

    [InverseProperty("CategoryStatus")]
    public virtual ICollection<CommodityCategory> CommodityCategories { get; set; } = new List<CommodityCategory>();
}