// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 桌位状态表
/// </summary>
[Table("dining_table_status_dict")]
[Index("StatusName", Name = "uk_dining_table_status_name", IsUnique = true)]
public partial class DiningTableStatusDict
{
    /// <summary>
    /// 桌位状态ID
    /// </summary>
    [Key]
    [Column("table_status_id")]
    public int TableStatusId { get; set; }

    /// <summary>
    /// 状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(50)]
    public string StatusName { get; set; }
}