// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 菜品分类表
/// </summary>
[Table("dish_category")]
[Index("DishSortOrder", Name = "idx_dish_category_sort_order")]
[Index("DishCategoryStatusId", Name = "idx_dish_category_status_id")]
[Index("DishCategoryName", Name = "uk_dish_category_name", IsUnique = true)]
public partial class DishCategory
{
    /// <summary>
    /// 菜品分类ID
    /// </summary>
    [Key]
    [Column("dish_category_id")]
    public int DishCategoryId { get; set; }

    /// <summary>
    /// 分类名称
    /// </summary>
    [Required]
    [Column("dish_category_name")]
    [StringLength(50)]
    public string DishCategoryName { get; set; }

    /// <summary>
    /// 排序号
    /// </summary>
    [Column("dish_sort_order")]
    public int DishSortOrder { get; set; }

    /// <summary>
    /// 菜品分类状态ID
    /// </summary>
    [Column("dish_category_status_id")]
    public int? DishCategoryStatusId { get; set; }

    [ForeignKey("DishCategoryStatusId")]
    [InverseProperty("DishCategories")]
    public virtual DishCategoryStatus DishCategoryStatus { get; set; }
}