// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManageAPI.Entity;

/// <summary>
/// 单位表
/// </summary>
[Table("unit")]
[Index("UnitCode", Name = "uk_unit_code", IsUnique = true)]
[Index("UnitName", Name = "uk_unit_name", IsUnique = true)]
public partial class Unit
{
    /// <summary>
    /// 单位ID
    /// </summary>
    [Key]
    [Column("unit_id")]
    public int UnitId { get; set; }

    /// <summary>
    /// 单位名称
    /// </summary>
    [Required]
    [Column("unit_name")]
    [StringLength(20)]
    public string UnitName { get; set; }

    /// <summary>
    /// 单位编码
    /// </summary>
    [Required]
    [Column("unit_code")]
    [StringLength(10)]
    public string UnitCode { get; set; }

    /// <summary>
    /// 1启用 0禁用
    /// </summary>
    [Column("is_enabled")]
    public sbyte IsEnabled { get; set; }
}
