// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

///// <summary>
///// 活动表
///// </summary>
//[Table("activity")]
//[Index("TypeId", Name = "fk_activity_activity_type_2")]
//[Index("StartDate", "EndDate", Name = "idx_activity_date")]
//[Index("SortOrder", Name = "idx_activity_sort")]
//[Index("StatusId", Name = "idx_activity_status_id")]
//public partial class Activity
//{
//    /// <summary>
//    /// 活动ID
//    /// </summary>
//    [Key]
//    [Column("activity_id")]
//    public long ActivityId { get; set; }

//    /// <summary>
//    /// 活动标题
//    /// </summary>
//    [Required]
//    [Column("title")]
//    [StringLength(255)]
//    public string Title { get; set; }

//    /// <summary>
//    /// 价格
//    /// </summary>
//    [Column("price")]
//    [Precision(10, 2)]
//    public decimal Price { get; set; }

//    /// <summary>
//    /// 开始日期
//    /// </summary>
//    [Column("start_date", TypeName = "datetime")]
//    public DateTime StartDate { get; set; }

//    /// <summary>
//    /// 结束日期
//    /// </summary>
//    [Column("end_date", TypeName = "datetime")]
//    public DateTime EndDate { get; set; }

//    /// <summary>
//    /// 活动图片
//    /// </summary>
//    [Required]
//    [Column("image_url")]
//    [StringLength(255)]
//    public string ImageUrl { get; set; }

//    /// <summary>
//    /// 活动视频
//    /// </summary>
//    [Column("video_url")]
//    [StringLength(500)]
//    public string VideoUrl { get; set; }

//    /// <summary>
//    /// 活动简介
//    /// </summary>
//    [Required]
//    [Column("description")]
//    [StringLength(1000)]
//    public string Description { get; set; }

//    /// <summary>
//    /// 活动地点
//    /// </summary>
//    [Required]
//    [Column("location")]
//    [StringLength(255)]
//    public string Location { get; set; }

//    /// <summary>
//    /// 活动报名上限人数
//    /// </summary>
//    [Column("people")]
//    public int People { get; set; }

//    /// <summary>
//    /// 活动内容
//    /// </summary>
//    [Column("content", TypeName = "text")]
//    public string Content { get; set; }

//    /// <summary>
//    /// 活动状态ID
//    /// </summary>
//    [Column("status_id")]
//    public int StatusId { get; set; }

//    /// <summary>
//    /// 排序
//    /// </summary>
//    [Column("sort_order")]
//    public int SortOrder { get; set; }

//    /// <summary>
//    /// 创建时间
//    /// </summary>
//    [Column("created_at", TypeName = "datetime")]
//    public DateTime CreatedAt { get; set; }

//    /// <summary>
//    /// 活动类型
//    /// </summary>
//    [Column("type_id")]
//    public int TypeId { get; set; }

//    [InverseProperty("Activity")]
//    public virtual ICollection<ActivityMaterial> ActivityMaterials { get; set; } = new List<ActivityMaterial>();

//    [InverseProperty("Activity")]
//    public virtual ICollection<ActivityOrderDetail> ActivityOrderDetails { get; set; } = new List<ActivityOrderDetail>();

//    [ForeignKey("StatusId")]
//    [InverseProperty("Activities")]
//    public virtual ActivityStatus Status { get; set; }

//    [ForeignKey("TypeId")]
//    [InverseProperty("Activities")]
//    public virtual ActivityType Type { get; set; }
//}