// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 活动订单明细表
/// </summary>
[Table("activity_order_detail")]
[Index("ActivityId", Name = "idx_activity_order_detail_activity_id")]
[Index("ActivityOrderId", Name = "idx_activity_order_detail_order_id")]
public partial class ActivityOrderDetail
{
    /// <summary>
    /// 活动订单明细ID
    /// </summary>
    [Key]
    [Column("activity_order_details_id")]
    public long ActivityOrderDetailsId { get; set; }

    /// <summary>
    /// 活动订单ID
    /// </summary>
    [Column("activity_order_id")]
    public long ActivityOrderId { get; set; }

    /// <summary>
    /// 活动ID
    /// </summary>
    [Column("activity_id")]
    public long ActivityId { get; set; }

    /// <summary>
    /// 单价
    /// </summary>
    [Column("unit_price")]
    [Precision(10, 2)]
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// 参与人数
    /// </summary>
    [Column("quantity")]
    public int Quantity { get; set; }

    /// <summary>
    /// 小计金额
    /// </summary>
    [Column("subtotal_amount")]
    [Precision(10, 2)]
    public decimal SubtotalAmount { get; set; }

    /// <summary>
    /// 核销码URL
    /// </summary>
    [Column("activity_qrcode")]
    [StringLength(255)]
    public string ActivityQrcode { get; set; }

    [ForeignKey("ActivityId")]
    [InverseProperty("ActivityOrderDetails")]
    public virtual ActivityEntity Activity { get; set; }

    [ForeignKey("ActivityOrderId")]
    [InverseProperty("ActivityOrderDetails")]
    public virtual ActivityOrder ActivityOrder { get; set; }

    [InverseProperty("ActivityOrderDetails")]
    public virtual ICollection<ActivityVerificationRecord> ActivityVerificationRecords { get; set; } = new List<ActivityVerificationRecord>();
}