// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 活动核销记录表
/// </summary>
[Table("activity_verification_record")]
[Index("ActivityOrderDetailsId", Name = "idx_activity_verification_detail_id")]
[Index("VerificationTime", Name = "idx_activity_verification_time")]
public partial class ActivityVerificationRecord
{
    /// <summary>
    /// 核销记录ID
    /// </summary>
    [Key]
    [Column("record_id")]
    public long RecordId { get; set; }

    /// <summary>
    /// 活动订单明细ID
    /// </summary>
    [Column("activity_order_details_id")]
    public long ActivityOrderDetailsId { get; set; }

    /// <summary>
    /// 核销时间
    /// </summary>
    [Column("verification_time", TypeName = "datetime")]
    public DateTime VerificationTime { get; set; }

    [ForeignKey("ActivityOrderDetailsId")]
    [InverseProperty("ActivityVerificationRecords")]
    public virtual ActivityOrderDetail ActivityOrderDetails { get; set; }
}