// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 商品分类表
/// </summary>
[Table("commodity_category")]
[Index("SortOrder", Name = "idx_category_sort_order")]
[Index("CategoryStatusId", Name = "idx_category_status_id")]
[Index("CategoryName", Name = "uk_category_name", IsUnique = true)]
public partial class CommodityCategory
{
    /// <summary>
    /// 分类ID
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// 分类名称
    /// </summary>
    [Required]
    [Column("category_name")]
    [StringLength(50)]
    public string CategoryName { get; set; }

    /// <summary>
    /// 分类描述
    /// </summary>
    [Required]
    [Column("category_description")]
    [StringLength(255)]
    public string CategoryDescription { get; set; }

    /// <summary>
    /// 分类状态ID
    /// </summary>
    [Column("category_status_id")]
    public int? CategoryStatusId { get; set; }

    /// <summary>
    /// 排序号
    /// </summary>
    [Column("sort_order")]
    public int SortOrder { get; set; }

    [ForeignKey("CategoryStatusId")]
    [InverseProperty("CommodityCategories")]
    public virtual CommodityCategoryStatus CategoryStatus { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Commodity> Commodities { get; set; } = new List<Commodity>();
}