// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 商品订单表
/// </summary>
[Table("commodity_orders")]
[Index("AddressId", Name = "idx_commodity_orders_address_id")]
[Index("CreateTime", Name = "idx_commodity_orders_create_time")]
[Index("OrderStatusId", Name = "idx_commodity_orders_status_id")]
[Index("TrackingTypeId", Name = "idx_commodity_orders_tracking_type_id")]
[Index("UserId", Name = "idx_commodity_orders_user_id")]
[Index("OrderNo", Name = "uk_commodity_orders_order_no", IsUnique = true)]
public partial class CommodityOrder
{
    /// <summary>
    /// 商品订单ID
    /// </summary>
    [Key]
    [Column("order_id")]
    public long OrderId { get; set; }

    /// <summary>
    /// 平台订单号
    /// </summary>
    [Required]
    [Column("order_no")]
    [StringLength(64)]
    public string OrderNo { get; set; }

    /// <summary>
    /// 微信支付订单号
    /// </summary>
    [Column("wx_pay_no")]
    [StringLength(500)]
    public string? WxPayNo { get; set; }

    /// <summary>
    /// 订单总金额
    /// </summary>
    [Column("total_amount")]
    [Precision(10, 2)]
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// 订单商品总数
    /// </summary>
    [Column("total_quantity")]
    public int TotalQuantity { get; set; }

    /// <summary>
    /// 订单状态ID
    /// </summary>
    [Column("order_status_id")]
    public int OrderStatusId { get; set; }

    /// <summary>
    /// 下单人ID
    /// </summary>
    [Column("user_id")]
    public int UserId { get; set; }

    /// <summary>
    /// 下单时间
    /// </summary>
    [Column("create_time", TypeName = "datetime")]
    public DateTime CreateTime { get; set; }

    /// <summary>
    /// 收货地址ID
    /// </summary>
    [Column("address_id")]
    public long? AddressId { get; set; }

    /// <summary>
    /// 快递单号
    /// </summary>
    [Column("tracking_number")]
    [StringLength(64)]
    public string? TrackingNumber { get; set; }

    /// <summary>
    /// 物流类型ID
    /// </summary>
    [Column("tracking_type_id")]
    public long? TrackingTypeId { get; set; }

    /// <summary>
    /// 收货人电话
    /// </summary>
    [Column("receiver_phone")]
    [StringLength(20)]
    public string? ReceiverPhone { get; set; }

    /// <summary>
    /// 配送方式（express=快递配送, pickup=到店自提）
    /// </summary>
    [Column("delivery_method")]
    [StringLength(20)]
    public string DeliveryMethod { get; set; } = "express";

    [InverseProperty("Order")]
    public virtual ICollection<CommodityOrderDetail> CommodityOrderDetails { get; set; } = new List<CommodityOrderDetail>();

    [ForeignKey("OrderStatusId")]
    [InverseProperty("CommodityOrders")]
    public virtual CommodityOrderStatus OrderStatus { get; set; }
}