// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Manage;

/// <summary>
/// 菜品状态表
/// </summary>
[Table("dish_status")]
[Index("StatusName", Name = "uk_dish_status_name", IsUnique = true)]
public partial class DishStatus
{
    /// <summary>
    /// 菜品状态ID
    /// </summary>
    [Key]
    [Column("dish_status_id")]
    public int DishStatusId { get; set; }

    /// <summary>
    /// 菜品状态名称
    /// </summary>
    [Required]
    [Column("status_name")]
    [StringLength(30)]
    public string StatusName { get; set; }
}